/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicRhythmRouteImport } from './routes/api.public.rhythm'
import { Route as ApiPublicRetentionRouteImport } from './routes/api.public.retention'
import { Route as ApiPublicHealthRouteImport } from './routes/api.public.health'
import { Route as ApiPublicHeadlineRouteImport } from './routes/api.public.headline'
import { Route as ApiPublicGridRouteImport } from './routes/api.public.grid'
import { Route as ApiPublicFeedRouteImport } from './routes/api.public.feed'
import { Route as ApiPublicActivityBucketsRouteImport } from './routes/api.public.activity-buckets'
import { Route as ApiPublicHooksIndexTickRouteImport } from './routes/api.public.hooks.index-tick'
import { Route as ApiPublicHooksHydrateTitlesRouteImport } from './routes/api.public.hooks.hydrate-titles'
import { Route as ApiPublicBeliefIdRouteImport } from './routes/api.public.belief.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRhythmRoute = ApiPublicRhythmRouteImport.update({
  id: '/api/public/rhythm',
  path: '/api/public/rhythm',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRetentionRoute = ApiPublicRetentionRouteImport.update({
  id: '/api/public/retention',
  path: '/api/public/retention',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHeadlineRoute = ApiPublicHeadlineRouteImport.update({
  id: '/api/public/headline',
  path: '/api/public/headline',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGridRoute = ApiPublicGridRouteImport.update({
  id: '/api/public/grid',
  path: '/api/public/grid',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFeedRoute = ApiPublicFeedRouteImport.update({
  id: '/api/public/feed',
  path: '/api/public/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicActivityBucketsRoute =
  ApiPublicActivityBucketsRouteImport.update({
    id: '/api/public/activity-buckets',
    path: '/api/public/activity-buckets',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksIndexTickRoute = ApiPublicHooksIndexTickRouteImport.update({
  id: '/api/public/hooks/index-tick',
  path: '/api/public/hooks/index-tick',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksHydrateTitlesRoute =
  ApiPublicHooksHydrateTitlesRouteImport.update({
    id: '/api/public/hooks/hydrate-titles',
    path: '/api/public/hooks/hydrate-titles',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicBeliefIdRoute = ApiPublicBeliefIdRouteImport.update({
  id: '/api/public/belief/$id',
  path: '/api/public/belief/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/activity-buckets': typeof ApiPublicActivityBucketsRoute
  '/api/public/feed': typeof ApiPublicFeedRoute
  '/api/public/grid': typeof ApiPublicGridRoute
  '/api/public/headline': typeof ApiPublicHeadlineRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/retention': typeof ApiPublicRetentionRoute
  '/api/public/rhythm': typeof ApiPublicRhythmRoute
  '/api/public/belief/$id': typeof ApiPublicBeliefIdRoute
  '/api/public/hooks/hydrate-titles': typeof ApiPublicHooksHydrateTitlesRoute
  '/api/public/hooks/index-tick': typeof ApiPublicHooksIndexTickRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/activity-buckets': typeof ApiPublicActivityBucketsRoute
  '/api/public/feed': typeof ApiPublicFeedRoute
  '/api/public/grid': typeof ApiPublicGridRoute
  '/api/public/headline': typeof ApiPublicHeadlineRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/retention': typeof ApiPublicRetentionRoute
  '/api/public/rhythm': typeof ApiPublicRhythmRoute
  '/api/public/belief/$id': typeof ApiPublicBeliefIdRoute
  '/api/public/hooks/hydrate-titles': typeof ApiPublicHooksHydrateTitlesRoute
  '/api/public/hooks/index-tick': typeof ApiPublicHooksIndexTickRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/activity-buckets': typeof ApiPublicActivityBucketsRoute
  '/api/public/feed': typeof ApiPublicFeedRoute
  '/api/public/grid': typeof ApiPublicGridRoute
  '/api/public/headline': typeof ApiPublicHeadlineRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/retention': typeof ApiPublicRetentionRoute
  '/api/public/rhythm': typeof ApiPublicRhythmRoute
  '/api/public/belief/$id': typeof ApiPublicBeliefIdRoute
  '/api/public/hooks/hydrate-titles': typeof ApiPublicHooksHydrateTitlesRoute
  '/api/public/hooks/index-tick': typeof ApiPublicHooksIndexTickRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/public/activity-buckets'
    | '/api/public/feed'
    | '/api/public/grid'
    | '/api/public/headline'
    | '/api/public/health'
    | '/api/public/retention'
    | '/api/public/rhythm'
    | '/api/public/belief/$id'
    | '/api/public/hooks/hydrate-titles'
    | '/api/public/hooks/index-tick'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/public/activity-buckets'
    | '/api/public/feed'
    | '/api/public/grid'
    | '/api/public/headline'
    | '/api/public/health'
    | '/api/public/retention'
    | '/api/public/rhythm'
    | '/api/public/belief/$id'
    | '/api/public/hooks/hydrate-titles'
    | '/api/public/hooks/index-tick'
  id:
    | '__root__'
    | '/'
    | '/api/public/activity-buckets'
    | '/api/public/feed'
    | '/api/public/grid'
    | '/api/public/headline'
    | '/api/public/health'
    | '/api/public/retention'
    | '/api/public/rhythm'
    | '/api/public/belief/$id'
    | '/api/public/hooks/hydrate-titles'
    | '/api/public/hooks/index-tick'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicActivityBucketsRoute: typeof ApiPublicActivityBucketsRoute
  ApiPublicFeedRoute: typeof ApiPublicFeedRoute
  ApiPublicGridRoute: typeof ApiPublicGridRoute
  ApiPublicHeadlineRoute: typeof ApiPublicHeadlineRoute
  ApiPublicHealthRoute: typeof ApiPublicHealthRoute
  ApiPublicRetentionRoute: typeof ApiPublicRetentionRoute
  ApiPublicRhythmRoute: typeof ApiPublicRhythmRoute
  ApiPublicBeliefIdRoute: typeof ApiPublicBeliefIdRoute
  ApiPublicHooksHydrateTitlesRoute: typeof ApiPublicHooksHydrateTitlesRoute
  ApiPublicHooksIndexTickRoute: typeof ApiPublicHooksIndexTickRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/rhythm': {
      id: '/api/public/rhythm'
      path: '/api/public/rhythm'
      fullPath: '/api/public/rhythm'
      preLoaderRoute: typeof ApiPublicRhythmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/retention': {
      id: '/api/public/retention'
      path: '/api/public/retention'
      fullPath: '/api/public/retention'
      preLoaderRoute: typeof ApiPublicRetentionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/headline': {
      id: '/api/public/headline'
      path: '/api/public/headline'
      fullPath: '/api/public/headline'
      preLoaderRoute: typeof ApiPublicHeadlineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/grid': {
      id: '/api/public/grid'
      path: '/api/public/grid'
      fullPath: '/api/public/grid'
      preLoaderRoute: typeof ApiPublicGridRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/feed': {
      id: '/api/public/feed'
      path: '/api/public/feed'
      fullPath: '/api/public/feed'
      preLoaderRoute: typeof ApiPublicFeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/activity-buckets': {
      id: '/api/public/activity-buckets'
      path: '/api/public/activity-buckets'
      fullPath: '/api/public/activity-buckets'
      preLoaderRoute: typeof ApiPublicActivityBucketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/index-tick': {
      id: '/api/public/hooks/index-tick'
      path: '/api/public/hooks/index-tick'
      fullPath: '/api/public/hooks/index-tick'
      preLoaderRoute: typeof ApiPublicHooksIndexTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/hydrate-titles': {
      id: '/api/public/hooks/hydrate-titles'
      path: '/api/public/hooks/hydrate-titles'
      fullPath: '/api/public/hooks/hydrate-titles'
      preLoaderRoute: typeof ApiPublicHooksHydrateTitlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/belief/$id': {
      id: '/api/public/belief/$id'
      path: '/api/public/belief/$id'
      fullPath: '/api/public/belief/$id'
      preLoaderRoute: typeof ApiPublicBeliefIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicActivityBucketsRoute: ApiPublicActivityBucketsRoute,
  ApiPublicFeedRoute: ApiPublicFeedRoute,
  ApiPublicGridRoute: ApiPublicGridRoute,
  ApiPublicHeadlineRoute: ApiPublicHeadlineRoute,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
  ApiPublicRetentionRoute: ApiPublicRetentionRoute,
  ApiPublicRhythmRoute: ApiPublicRhythmRoute,
  ApiPublicBeliefIdRoute: ApiPublicBeliefIdRoute,
  ApiPublicHooksHydrateTitlesRoute: ApiPublicHooksHydrateTitlesRoute,
  ApiPublicHooksIndexTickRoute: ApiPublicHooksIndexTickRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
